/**
 * HOSSAM LICENSE MANAGER PRO — js/repositories/ActivationCodesRepository.js
 * PHASE C v3/v3.1/v3.2 — local bookkeeping of Phase C Activation Codes
 * generated by this tool for a customer's license.
 *
 * Mirrors the fixed, already-approved design decisions exactly (see
 * PHASE_C_V3_DESIGN_PLAN.md §2/§6): 128-bit entropy, Base32 Crockford,
 * formatted groups of 4, normalized before hashing, SHA-256 hash stored
 * — the plaintext code is NEVER persisted anywhere, including here; it
 * exists only transiently in the return value of generateForLicense()
 * so the operator can copy/share it once.
 *
 * This tool "has no server" (see LicensesRepository.js's own header
 * comment) — there is no network channel to elhossam's Apps Script
 * backend. The authoritative record lives in elhossam's "أكواد_التفعيل"
 * sheet, populated by the operator manually pasting the row produced by
 * buildActivationCodeSheetRow() below, exactly the same manual-transfer
 * pattern already established by LicensesRepository.buildRevokeSheetRow()
 * for license revocation.
 */
(function (window) {
  'use strict';

  var CROCKFORD_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'; // excludes I, L, O, U

  /** Encodes a byte array as Crockford Base32 (5 bits/symbol, no padding
   *  characters — the final partial group is zero-padded on the right,
   *  the standard Crockford convention). */
  function toCrockfordBase32(bytes) {
    var bits = 0, value = 0, output = '';
    for (var i = 0; i < bytes.length; i++) {
      value = (value << 8) | bytes[i];
      bits += 8;
      while (bits >= 5) {
        output += CROCKFORD_ALPHABET[(value >>> (bits - 5)) & 31];
        bits -= 5;
      }
    }
    if (bits > 0) {
      output += CROCKFORD_ALPHABET[(value << (5 - bits)) & 31];
    }
    return output;
  }

  /** Same normalization rule as Config/11_Auth.gs's _normalizeActivationCode_()
   *  on the server — MUST stay identical on both sides, or a correctly
   *  generated code would never hash-match at registration time. */
  function normalize(code) {
    return String(code || '').trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
  }

  /** Cosmetic grouping only (for the operator to read/copy/transcribe) —
   *  stripped again by normalize() before hashing, so an uneven final
   *  group is harmless. */
  function groupBy4(s) {
    return (s.match(/.{1,4}/g) || [s]).join('-');
  }

  function ActivationCodesRepository() {
    window.HLMRepository.call(this, 'activationCodes', 'أكواد التفعيل');
  }
  ActivationCodesRepository.prototype = Object.create(window.HLMRepository.prototype);

  ActivationCodesRepository.prototype.forLicense = async function (licenseId) {
    var rows = await this.getByIndex('licenseId', licenseId);
    rows.sort(function (a, b) { return new Date(b.createdAt) - new Date(a.createdAt); });
    return rows;
  };

  /**
   * Generates one new Activation Code for a license.
   * @param {{licenseId:string, customerId?:string, expiresAt?:string}} opts
   * @returns {Promise<{record:Object, plaintextCode:string}>} `plaintextCode`
   *   is grouped-for-display (e.g. "ABCD-1234-EFGH-...") and is NOT stored
   *   anywhere by this call — the caller must show/copy it immediately.
   */
  ActivationCodesRepository.prototype.generateForLicense = async function (opts, actor) {
    if (!window.HLMCrypto || !window.HLMCrypto.isAvailable()) {
      throw new Error('crypto_unavailable');
    }
    if (!opts || !opts.licenseId) {
      throw new Error('licenseId_required');
    }
    var bytes = new Uint8Array(16); // 128-bit entropy, per the fixed design decision
    if (!(window.crypto && window.crypto.getRandomValues)) {
      throw new Error('crypto_unavailable');
    }
    window.crypto.getRandomValues(bytes);

    var rawCode = toCrockfordBase32(bytes); // 26 chars, ungrouped
    var normalized = normalize(rawCode);
    var activationCodeHash = await window.HLMCrypto.sha256Hex(normalized);

    var record = await this.create({
      licenseId: opts.licenseId,
      customerId: opts.customerId || '',
      activationCodeHash: activationCodeHash,
      status: 'unused',
      expiresAt: opts.expiresAt || ''
    }, actor);

    return { record: record, plaintextCode: groupBy4(rawCode) };
  };

  /** Marks a locally-tracked code as revoked (bookkeeping only — the
   *  authoritative status lives in elhossam's sheet; the operator must
   *  also update that row manually, same caveat as license revocation). */
  ActivationCodesRepository.prototype.revoke = async function (id, actor) {
    return this.update(id, { status: 'revoked' }, actor);
  };

  /** Row to paste into the project's Google Sheet "أكواد_التفعيل" tab —
   *  same manual-transfer pattern as LicensesRepository.buildRevokeSheetRow()
   *  (see this file's header comment for why: this tool has no server). */
  ActivationCodesRepository.prototype.buildActivationCodeSheetRow = function (record) {
    return {
      id: record.id,
      licenseId: record.licenseId,
      activationCodeHash: record.activationCodeHash,
      status: record.status,
      createdAt: record.createdAt,
      expiresAt: record.expiresAt || '',
      usedAt: '',
      installationId: ''
    };
  };

  window.HLMActivationCodesRepository = new ActivationCodesRepository();
  // Exposed for the Node test harness (js/tests/PHASE_C_lmp_activationcodes_tests.js)
  // only — not used by any application code path.
  window.HLMActivationCodesRepository._internal = { toCrockfordBase32: toCrockfordBase32, normalize: normalize, groupBy4: groupBy4 };
})(typeof window !== 'undefined' ? window : globalThis);
